package com.syncechron.exceptiondemo.noexception;

public class ExceptionTest {
	
	int number1 = 10;
	int number2 = 0;
	
	public void divideNumber() {
		
		int number3 = number1/number2;
		System.out.println("Result: " + number3);
		
	}

}
